name: wynote
description: A Flutter note-taking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  flutter_quill: ^9.5.0
  flutter_quill_extensions: ^9.3.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
