name: Build WyNote APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: false

      - name: Flutter Version
        run: flutter --version

      - name: Flutter Clean
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Upgrade to V2 Packages
        run: flutter pub upgrade

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wynote-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
